# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- test_azure_pipelines1

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt-get install -y fftw3-dev liblcms2-dev libboost-all-dev libcgal-dev liblzma-dev
  displayName: 'Install prereqs'

- script: |
    cd uxbuild
    install_dir=$HOME/app/cuemol2
    debug="--disable-debug --enable-m64"
    usepybr="--disable-python"
    usexrbr="--without-xmlrpc"
    lcms="--with-lcms"
    xz="--with-xz"
    config_scr=../src/configure
    if test ! -f $config_scr; then
    (
        cd ../src
        aclocal; libtoolize; aclocal; autoheader; automake -a; autoconf;
        cd js
        aclocal; libtoolize; aclocal; autoheader; automake -a; autoconf;
    )
    fi
    env CC=gcc CXX=g++ CXXFLAGS="-std=c++0x -O" \
    $config_scr \
    --disable-static \
    --enable-shared \
    --prefix=$install_dir \
    $lcms \
    $xz \
    $usepybr \
    $usexrbr \
    --enable-cli \
    --with-boost \
    --with-fftw \
    --with-cgal \
    $debug
  displayName: 'Run a configure script'

- script: |
    make
    make install
  displayName: 'build and install'
