# https://taskfile.dev

version: '3'

vars:
  WORKDIR: '{{if eq OS "windows"}}c:\tmp\proj64_deplibs{{else}}$HOME/tmp/proj64_deplibs{{end}}'
  LIBCUEMOL2_BUILDDIR: '{{if eq OS "windows"}}{{.WORKDIR}}/tmp/build_libcuemol2{{else}}{{.WORKDIR}}/build_libcuemol2{{end}}'
  LIBCUEMOL2_INSTDIR: "{{.WORKDIR}}/cuemol2"
  CONFIG: '{{if eq OS "windows"}}Release{{else}}Debug{{end}}'
  PARALLEL: ""
  EMBED_PYTHON_ROOT:
    sh: '[ -d "{{.WORKDIR}}/python" ] && echo "{{.WORKDIR}}/python" || echo ""'

tasks:
  default:
    cmds:
      - echo "Default workdir {{.WORKDIR}}"
    silent: true

  #####

  download_deplibs:
    cmds:
      - bash download_deplibs/run.sh "{{.WORKDIR}}" macOS ARM64

  download_extpkgs:
    cmds:
      - bash download_extpkgs/run.sh "{{.WORKDIR}}" macOS ARM64

  #####

  rebuild_libcuemol2:
    desc: "Config & Rebuild libcuemol2"
    deps:
      - task: rebuild_libcuemol2:{{OS}}

  rebuild_libcuemol2:darwin:
    platforms: [darwin]
    env:
      EMBED_PYTHON_ROOT: '{{.EMBED_PYTHON_ROOT | default (env "EMBED_PYTHON_ROOT")}}'
    cmds:
      - bash build_libcuemol2_posix/run.sh "{{.WORKDIR}}" "{{.CONFIG}}"

  rebuild_libcuemol2:linux:
    platforms: [linux]
    env:
      EMBED_PYTHON_ROOT: '{{.EMBED_PYTHON_ROOT | default (env "EMBED_PYTHON_ROOT")}}'
    cmds:
      - bash build_libcuemol2_posix/run.sh "{{.WORKDIR}}" "{{.CONFIG}}"

  rebuild_libcuemol2:windows:
    platforms: [windows]
    cmds:
      - cmd /c build_libcuemol2_win.bat "{{.WORKDIR}}" "{{.CONFIG}}"

  build_libcuemol2:
    desc: "Build libcuemol2 (using current config)"
    deps:
      - task: build_libcuemol2:{{OS}}

  build_libcuemol2:darwin:
    desc: "Rebuild libcuemol2 (without running setup/config)"
    platforms: [darwin]
    cmds:
      - cmake --build "{{.LIBCUEMOL2_BUILDDIR}}" --parallel "{{.PARALLEL}}" --config "{{.CONFIG}}" --target install

  build_libcuemol2:linux:
    desc: "Rebuild libcuemol2 (without running setup/config)"
    platforms: [linux]
    cmds:
      - cmake --build "{{.LIBCUEMOL2_BUILDDIR}}" --parallel "{{.PARALLEL}}" --config "{{.CONFIG}}" --target install

  build_libcuemol2:windows:
    platforms: [windows]
    cmds:
      - cmake --build "{{.LIBCUEMOL2_BUILDDIR}}" --parallel "{{.PARALLEL}}" --config "{{.CONFIG}}" --target install

  clean_libcuemol2:
    desc: "Clean up the libcuemol2 obj dir"
    cmds:
      - rm -rf "{{.LIBCUEMOL2_BUILDDIR}}"
      - rm -rf "{{.LIBCUEMOL2_INSTDIR}}"

  clean_shaders:
    desc: "Clean up the libcuemol2 shader files"
    cmds:
      - find "{{.LIBCUEMOL2_BUILDDIR}}" -name "*.glsl" | xargs rm
      - find "{{.LIBCUEMOL2_INSTDIR}}" -name "*.glsl" | xargs rm

#####

  build_pytest:
    deps:
      - task: build_pytest:{{OS}}

  build_pytest:darwin:
    platforms: [darwin]
    cmds:
      - task: build_libcuemol2
      - bash build_pymod_posix/run.sh "{{.WORKDIR}}" "{{.CONFIG}}"

#####

  build_nodejs:
    deps:
      - task: build_nodejs:{{OS}}

  build_nodejs:darwin:
    platforms: [darwin]
    cmds:
      - task: build_libcuemol2
      - bash build_nodejs_posix/run.sh "{{.WORKDIR}}" "{{.CONFIG}}"

  build_nodejs:windows:
    platforms: [windows]
    cmds:
      - task: build_libcuemol2
      - cmd /c build_nodejs_posix\\run_win.bat "{{.WORKDIR}}"

#####

  build_cli:
    deps:
      - task: build_cli:{{OS}}

  build_cli:darwin:
    platforms: [darwin]
    cmds:
      - task: build_libcuemol2
      - bash build_cuetty_posix/run.sh "{{.WORKDIR}}" "{{.CONFIG}}"

  run_cli:
    platforms: [darwin]
    cmds:
      # - task: build_cli
      - env LD_LIBRARY_PATH="{{.WORKDIR}}/cuemol2/lib" "{{.WORKDIR}}/cuemol2/bin/cuetty" -i

#####

  build_uxpgui:
    desc: "Setup, config, and build the uxpgui app"
    platforms: [darwin]
    cmds:
      - bash build_uxpgui_posix/run.sh "{{.WORKDIR}}" macOS ARM64

  rebuild_uxpgui:
    desc: "Rebuild the uxpgui app (without running setup/config)"
    platforms: [darwin]
    dir: "{{.ROOT_DIR}}/../uxp_gui/"
    cmds:
      - ./mach build

  run_uxpgui:
    desc: "Run the built uxpgui app"
    platforms: [darwin]
    dir: "{{.ROOT_DIR}}/../uxp_gui/"
    cmds:
      - ./obj-aarch64-apple-darwin/dist/CueMol2.app/Contents/MacOS/cuemol2

  clean_uxpgui:
    desc: "Clean up uxpgui obj dir"
    cmds:
      - rm -rf "{{.ROOT_DIR}}/../uxp_gui/obj-*"

#####

  uxpgui:
    desc: "Build libcuemol2 and uxp and run the built app"
    platforms: [darwin]
    cmds:
      - task: rebuild_libcuemol2
      - task: rebuild_uxpgui
      - task: run_uxpgui
