name: 'Build UXP GUI posix'
description: 'Build UXP GUI posix'

env:
  pyenv27-cache-version: v1

inputs:
  basedir:
     description: 'base dir'
     required: true

outputs:
  artifact-path:
    description: 'built file'
    value: ${{ steps.create-artifact.outputs.artifact-path }}

runs:
  using: "composite"
  steps:

  - name: Set HOME variable
    shell: bash
    run: |
      echo "USER_HOME=$HOME" >> $GITHUB_ENV
      echo "PYENV_ROOT=$HOME/.pyenv" >> $GITHUB_ENV

  - name: Populate pyenv27 cache
    id: cache-pyenv27
    uses: actions/cache@v4
    with:
      path: ${{ env.PYENV_ROOT }}
      key: pyenv27-${{ runner.os }}-${{ runner.arch }}-${{ env.pyenv27-cache-version }}

  - name: Install python2
    if: steps.cache-pyenv27.outputs.cache-hit != 'true'
    shell: bash
    run: |
      export PYENV_ROOT="$HOME/.pyenv"
      brew install pyenv zlib
      command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      env LDFLAGS="-L$(brew --prefix zlib)/lib" CPPFLAGS="-I$(brew --prefix zlib)/include" PKG_CONFIG_PATH="$(brew --prefix zlib)/lib/pkgconfig" pyenv install 2.7.18

  - name: Check pyenv
    shell: bash
    run: |
      ls -la $PYENV_ROOT
      brew install pyenv zlib
      command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      echo $PYENV_ROOT
      export PYENV_ROOT="$HOME/.pyenv"
      eval "$(pyenv init -)"
      pyenv global 2.7.18
      pyenv versions
      python --version

  - name: Build UXP GUI
    id: create-artifact
    shell: bash
    env:
      SCCACHE_GHA_ENABLED: "true"
      SCCACHE_GHA_VERSION: "${{ env.RUNNER_TYPE }}"
      ARTIFACT_NAME: cuemol2_${{ runner.os }}_${{ runner.arch }}.tar.bz2
    run: |
      export PYENV_ROOT="$HOME/.pyenv"
      command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
      pyenv global 2.7.18

      cd ${GITHUB_WORKSPACE}
      sccache --show-stats
      echo "SCCACHE_GHA_VERSION: $SCCACHE_GHA_VERSION"
      which python
      python --version
      bash build_scripts/build_uxpgui_posix/run.sh ${{ inputs.basedir }} ${{ runner.os }} ${{ runner.arch }}

      sccache --show-stats
      ls -l ${GITHUB_WORKSPACE}/${ARTIFACT_NAME}
      echo "artifact-path=${GITHUB_WORKSPACE}/${ARTIFACT_NAME}" >> $GITHUB_OUTPUT
