name: 'Build libcuemol2 posix'
description: 'Build libcuemol2 posix'

inputs:
  basedir:
     description: 'base dir'
     required: true

runs:
  using: "composite"
  steps:
  - name: Install prerequsites (posix)
    if: runner.os != 'Windows'
    shell: bash
    run: |
      if [ ${{ runner.os }} = "macOS" ]; then
        brew install bison
        echo "brew prefix: $(brew --prefix)"
        export PATH="$(brew --prefix)/opt/bison/bin:$PATH"
      elif [ ${{ runner.os }} = "Linux" ]; then
        echo "Linux ${{ runner.os }}"
      else
        echo "unknown runner os: ${{ runner.os }}"
        exit 1
      fi
      bison --version

  - name: Install prerequsites (Windows)
    if: runner.os == 'Windows'
    shell: powershell
    run: |
      choco install -y -r wget winflexbison3

      $mozilladir = "c:\mozilla-build"
      $src_url = "https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-3.4.exe"
      if((Test-Path $mozilladir) -eq "True"){
        Write-Host "Cache exists"
        dir $mozilladir
      }else{
        Start-BitsTransfer -Source $src_url -Destination ./MozillaBuildSetup.exe
        .\MozillaBuildSetup.exe /S | Out-Null
      }
      dir $mozilladir

  - name: Build libcuemol2
    if: runner.os != 'Windows'
    shell: bash
    env:
      SCCACHE_GHA_ENABLED: "true"
      SCCACHE_GHA_VERSION: "${{ env.RUNNER_TYPE }}"
    run: |
      cd ${GITHUB_WORKSPACE}
      sccache --show-stats
      if [ ${{ runner.os }} = "macOS" ]; then
        export PATH="$(brew --prefix)/opt/bison/bin:$PATH"
      fi
      bash build_scripts/build_libcuemol2_posix/run.sh ${{ inputs.basedir }} ${{ runner.os }} ${{ runner.arch }}
      sccache --show-stats

  - name: Build libcuemol2
    if: runner.os == 'Windows'
    shell: cmd
    run: |
      echo on
      cd %GITHUB_WORKSPACE%
      SET BASEDIR=${{ inputs.basedir }}
      dir %BASEDIR%
      cmd /c %GITHUB_WORKSPACE%\build_scripts\build_libcuemol2_win.bat %BASEDIR% Release
