#!/usr/bin/env python

import argparse

from pathlib import Path


def arg_parser():
    parser = argparse.ArgumentParser(description="make wrapper table js file")
    parser.add_argument("--output_js", type=str)
    parser.add_argument("--output_ts", type=str)
    parser.add_argument("--input_dir", type=str, default="results")
    args = parser.parse_args()
    return args


def main():
    args = arg_parser()
    input_dir = Path(args.input_dir).resolve()
    subdir = "."

    if args.output_ts:
        outfile = args.output_ts
        mode = "ts"
    elif args.output_js:
        outfile = args.output_js
        mode = "js"
    else:
        raise Exception("must specify --output_js or --output_ts")

    with open(outfile, "w") as f:
        f.write("// autogenerated by make_wrapper_table.py\n")
        f.write("\n")
        print(f"input_dir: {input_dir}")

        if mode == "ts":
            file_list = sorted(list(input_dir.glob("*.ts")))
        else:
            file_list = sorted(list(input_dir.glob("*.js")))

        file_list = [x for x in file_list if x.stem != "wrapper_loader"]
        for in_js in file_list:
            stem = in_js.stem
            if mode == "ts":
                f.write(f"import {{ {stem} }} from '{subdir}/{stem}';\n")
            else:
                f.write(f"import {{ {stem} }} from '{subdir}/{stem}.js';\n")

        f.write("\n")
        f.write("\n")
        if mode == "ts":
            f.write("const wrapper_map: Record<string, any> = {\n")
        else:
            f.write("const wrapper_map = {\n")

        for in_js in file_list:
            stem = in_js.stem
            f.write(f"    '{stem}': {stem},\n")

        f.write("};\n")
        f.write("\n")
        f.write("export { wrapper_map };\n")
        f.write("\n")

    print(f"output {args.output_js} ok")


if __name__ == "__main__":
    main()
