#include <gtest/gtest.h>
#include <common.h>
#include "surface/MSMSFileReader.hpp"
#include "qsys/ObjReader.hpp"
#include <qlib/StringStream.hpp>
#include <string>

using surface::MSMSFileReader;
using qsys::ObjReader;
using qlib::StrInStream;

namespace {

int sniff(const ObjReader &reader, const std::string &payload)
{
    StrInStream ins(payload.data(), static_cast<int>(payload.size()));
    return reader.canHandleContent(ins);
}

}  // namespace

// ----------------------------------------------------------------------
// MSMSFileReader::canHandleContent
// ----------------------------------------------------------------------

TEST(MSMSFileReaderSniffTest, HeaderLineReturnsYes)
{
    MSMSFileReader reader;
    // Typical MSMS .face / .vert header emitted by the MSMS program.
    const std::string payload =
        "# MSMS solvent excluded surface vertices ... radius = 1.500\n"
        "#faces  #sphere density probe_r\n"
        "  1234  1.4 1.4\n";
    EXPECT_EQ(sniff(reader, payload), ObjReader::CONTENT_YES);
}

TEST(MSMSFileReaderSniffTest, EmptyReturnsUnknown)
{
    MSMSFileReader reader;
    EXPECT_EQ(sniff(reader, std::string()), ObjReader::CONTENT_UNKNOWN);
}

TEST(MSMSFileReaderSniffTest, BinaryReturnsUnknown)
{
    MSMSFileReader reader;
    const std::string payload(216, '\0');
    EXPECT_EQ(sniff(reader, payload), ObjReader::CONTENT_UNKNOWN);
}

TEST(MSMSFileReaderSniffTest, PdbReturnsUnknown)
{
    MSMSFileReader reader;
    const std::string payload =
        "HEADER    PROTEIN                                   01-JAN-00\n"
        "ATOM      1  N   ALA A   1       0.000   0.000   0.000\n";
    EXPECT_EQ(sniff(reader, payload), ObjReader::CONTENT_UNKNOWN);
}

TEST(MSMSFileReaderSniffTest, CommentsWithoutMsmsMarkerReturnsUnknown)
{
    MSMSFileReader reader;
    // Leading comments present but none mention MSMS, then a
    // non-comment line ends the scan.
    const std::string payload =
        "# generated by other tool\n"
        "# version 1.0\n"
        "  1234  1.4 1.4\n";
    EXPECT_EQ(sniff(reader, payload), ObjReader::CONTENT_UNKNOWN);
}
