#include <gtest/gtest.h>
#include <common.h>
#include "importers/MOL2MolReader.hpp"
#include "qsys/ObjReader.hpp"
#include <qlib/StringStream.hpp>
#include <string>

using importers::MOL2MolReader;
using qsys::ObjReader;
using qlib::StrInStream;

namespace {

int sniff(const ObjReader &reader, const std::string &payload)
{
    StrInStream ins(payload.data(), static_cast<int>(payload.size()));
    return reader.canHandleContent(ins);
}

}  // namespace

// ----------------------------------------------------------------------
// MOL2MolReader::canHandleContent
// ----------------------------------------------------------------------

TEST(MOL2MolReaderSniffTest, TriposMoleculeAtStartReturnsYes)
{
    MOL2MolReader reader;
    const std::string payload =
        "@<TRIPOS>MOLECULE\n"
        "ligand\n"
        "3 2 1 0 0\n"
        "SMALL\n"
        "USER_CHARGES\n"
        "@<TRIPOS>ATOM\n"
        "1 N 0.0 0.0 0.0 N.am 1 LIG -0.6\n";
    EXPECT_EQ(sniff(reader, payload), ObjReader::CONTENT_YES);
}

TEST(MOL2MolReaderSniffTest, TriposMoleculeAfterCommentReturnsYes)
{
    MOL2MolReader reader;
    // MOL2 may have leading lines before the first section marker
    // (the parser scans forward to find @<TRIPOS>MOLECULE).
    const std::string payload =
        "# generated by mol2 writer\n"
        "# version 1\n"
        "@<TRIPOS>MOLECULE\n"
        "ligand\n";
    EXPECT_EQ(sniff(reader, payload), ObjReader::CONTENT_YES);
}

TEST(MOL2MolReaderSniffTest, EmptyReturnsUnknown)
{
    MOL2MolReader reader;
    EXPECT_EQ(sniff(reader, std::string()), ObjReader::CONTENT_UNKNOWN);
}

TEST(MOL2MolReaderSniffTest, BinaryReturnsUnknown)
{
    MOL2MolReader reader;
    // No "@<TRIPOS>MOLECULE" line in binary -> UNKNOWN.
    const std::string payload(216, '\0');
    EXPECT_EQ(sniff(reader, payload), ObjReader::CONTENT_UNKNOWN);
}

TEST(MOL2MolReaderSniffTest, PdbReturnsUnknown)
{
    MOL2MolReader reader;
    const std::string payload =
        "HEADER    PROTEIN                                   01-JAN-00\n"
        "ATOM      1  N   ALA A   1       0.000   0.000   0.000  1.00  0.00\n";
    EXPECT_EQ(sniff(reader, payload), ObjReader::CONTENT_UNKNOWN);
}
