name: 'Build node.js addon posix'
description: 'Build node.js addon posix'

inputs:
  basedir:
     description: 'base dir'
     required: true

runs:
  using: "composite"
  steps:
  - name: Build and install node.js addon
    shell: bash
    # env:
    #   SCCACHE_GHA_ENABLED: "true"
    run: |
      cd ${GITHUB_WORKSPACE}
      bash build_scripts/build_nodejs_posix/run.sh ${{ inputs.basedir }}
