[project]
name = "cuemol2"
version = "0.0.1"

[build-system]
requires = ["scikit-build-core", "numpy"]
build-backend = "scikit_build_core.build"

[tool.scikit-build-core]
wheel.py-api = "cp37"

[tool.scikit-build]
build-dir = "build/{wheel_tag}"
# cmake.args = ["-G", "Unix Makefiles"]
cmake.args = ["-G", "Ninja"]
wheel.packages = ["python/cuemol", "cuemol_internal"]
# cmake.install-dir = "mypackage"
wheel.install-dir = "cuemol_internal"

# [tool.scikit-build.cmake.define]
# LIBCUEMOL2_ROOT =

# [tool.scikit-build.wheel.packages]
# "example/mypackage" =

[tool.black]
line-length = 88
target-version = ["py38"]

[tool.isort]
default_section = "THIRDPARTY"
ensure_newline_before_comments = true
force_grid_wrap = 0
force_single_line = false
include_trailing_comma = true
known_first_party = ["cuemol2", "cuemol2_internal"]
line_length = 88
multi_line_output = 3
use_parentheses = true
