/**
 * @file types.ts
 * @description Shared TypeScript type definitions used across the application.
 *
 * All types in this module are pure data shapes (no logic or side-effects).
 * Importing from here instead of defining types inline in components keeps
 * the codebase consistent and makes cross-component data flows easy to trace.
 *
 * @module types
 */

import type { AppIconKey } from "./data/appIcons";

// ────────────────────────────────────────────────────────────
// Scene / File-tree
// ────────────────────────────────────────────────────────────

/**
 * A single node in a generic tree displayed by `TreeView`.
 *
 * The tree is recursive: each node may contain an arbitrary number of
 * child nodes, enabling multi-level hierarchies (e.g. Scene → Object →
 * Renderer, or Chain → Residue → Atom).
 */
export interface TreeNodeData {
  /** Stable, unique identifier for the node within its tree. */
  id: string;

  /** Human-readable display name shown in the tree row. */
  label: string;

  /** Semantic icon key rendered to the left of the label (see `AppIcon`). */
  icon: AppIconKey;

  /** Ordered list of child nodes. Empty array indicates a leaf node. */
  children: TreeNodeData[];

  /**
   * Optional secondary text shown to the right of the label (e.g. a
   * residue count, file size, or status indicator).
   */
  secondaryLabel?: string;
}

// ────────────────────────────────────────────────────────────
// Editor tabs
// ────────────────────────────────────────────────────────────

import type { RenderResult } from "./data/renderResult";

/**
 * Discriminator for tab types.
 *
 * | Type             | Rendered as                              |
 * |------------------|------------------------------------------|
 * | `"welcome"`      | WelcomePane (start screen)               |
 * | `"settings"`     | SettingsPane (application settings)      |
 * | `"molview"`      | MolViewPane (WebGL molecule view)        |
 * | `"renderResult"` | RenderResultPane (completed render)      |
 */
export type TabType = "welcome" | "settings" | "molview" | "renderResult";

/**
 * Metadata for a single editor tab.
 */
export interface TabData {
  /** Stable, unique identifier generated at tab-creation time. */
  id: string;

  /** Label shown on the tab strip. */
  title: string;

  /** Semantic icon key for the tab label (see `AppIcon`). */
  icon: AppIconKey;

  /**
   * Discriminator for tab type.
   */
  type?: TabType;

  /**
   * CueMol view ID associated with this tab.
   * Present only for tabs with `type === "molview"`.
   */
  viewId?: number;

  /**
   * Completed render data.
   * Present only for tabs with `type === "renderResult"`.
   */
  renderResult?: RenderResult;
}

// ────────────────────────────────────────────────────────────
// Logging
// ────────────────────────────────────────────────────────────

/**
 * A single structured log entry displayed in `LogReplDraft` (a draft
 * REPL-enabled Output panel not yet wired into the app).
 *
 * Entries are created by `App.addLog` and are intentionally immutable
 * once appended to the log list.
 */
export interface LogEntry {
  /**
   * Timestamp string in `HH:MM:SS` format (local time, zero-padded).
   * Generated by `nowTimestamp()` in `App.tsx` at the moment the entry
   * is created.
   */
  time: string;

  /**
   * Severity level of the log message.
   *
   * | Level   | Intended use                          |
   * |---------|---------------------------------------|
   * | `INFO`  | Normal operational messages           |
   * | `WARN`  | Recoverable issues or deprecations    |
   * | `ERROR` | Failures that affect functionality    |
   * | `DEBUG` | Verbose diagnostics (dev only)        |
   */
  level: "INFO" | "WARN" | "ERROR" | "DEBUG";

  /** Human-readable description of the event. */
  msg: string;
}

// ────────────────────────────────────────────────────────────
// Animation Timeline (Blender-style strip model)
// ────────────────────────────────────────────────────────────
//
// CueMol's animation is an ordered list of time-ranged `AnimObj` elements
// owned by the scene's `AnimMgr`; every time value is in milliseconds. Each
// element becomes one horizontal strip on the timeline (left = absStart,
// width = duration). These types are driven 1:1 by the C++ AnimMgr/AnimObj
// API.

/**
 * Concrete `AnimObj` subtype.
 *
 * `AnimObj` exposes no `type` getter, so the worker derives this from the
 * wrapped object's class name (see `helpers/animElementType.ts`).
 * `'unknown'` is the fallback bucket for an unrecognised subtype.
 */
export type AnimElementType =
  | "SimpleSpin"
  | "CamMotion"
  | "ShowHideAnim"
  | "SlideInOutAnim"
  | "MolAnim"
  | "RealPropAnim"
  | "RendXformAnim"
  | "NoopAnimObj"
  | "unknown";

/**
 * Add-menu element type id. Maps to a concrete `AnimObj` subclass worker-side
 * (Show/Hide -> ShowHideAnim, SlideIn/Out -> SlideInOutAnim, each with a `hide`
 * flag); the others map by name. Distinct from `AnimElementType` because the
 * menu splits Show/Hide and SlideIn/Out that share one class.
 */
export type AnimAddType =
  | "SimpleSpin"
  | "CamMotion"
  | "ShowAnim"
  | "HideAnim"
  | "SlideInAnim"
  | "SlideOutAnim"
  | "MolAnim"
  | "NoopAnimObj";

/** Playback state of the animation manager. */
export type AnimPlayState = "stop" | "play" | "pause";

/**
 * One CueMol `AnimObj` rendered as a single timeline strip.
 *
 * All time fields are milliseconds (`TimeValue.millisec`). The strip is
 * drawn from the resolved `absStartMs`..`absEndMs` span; edits (later
 * phases) write the *relative* `startMs`/`endMs` and the worker re-resolves
 * via `AnimMgr.resolveRelTime()`.
 */
export interface AnimElement {
  /** Position in `AnimMgr` (== `getAt` index). Volatile across edits. */
  index: number;

  /** `AnimObj.uid` -- stable identity (React key / selection). */
  uid: number;

  /** `AnimObj.name`. Also the target of another element's `timeRefName`. */
  name: string;

  /** Subtype, derived worker-side from the class name (not a C++ prop). */
  type: AnimElementType;

  /** `AnimObj.disabled` (enabled = `!disabled`). */
  disabled: boolean;

  /** `AnimObj.timeRefName` -- '' = absolute; else chained after that element. */
  timeRefName: string;

  /** Relative start (what edits write). */
  startMs: number;

  /** Relative end. */
  endMs: number;

  /** Resolved absolute start -> strip left edge (read-only in C++). */
  absStartMs: number;

  /** Resolved absolute end -> strip right edge (read-only in C++). */
  absEndMs: number;

  /** `AnimObj.quadric` easing factor (0 = linear). */
  quadric: number;
}

/**
 * Manager-level `AnimMgr` snapshot.
 *
 * `elapsedMs` has no change event on the C++ side, so it is polled during
 * playback (later phases) rather than pushed.
 */
export interface AnimMgrState {
  /** Total length (`AnimMgr.length`; auto-grows to `max(absEnd)`). */
  lengthMs: number;

  /** Current play position (`AnimMgr.elapsed`). */
  elapsedMs: number;

  /** Play state, mapped from the `playState` enum. */
  playState: AnimPlayState;

  /** `AnimMgr.loop`. */
  loop: boolean;

  /** `AnimMgr.startcam` (start-camera name; '' when none). */
  startcam: string;
}

/** Full timeline snapshot rendered by `AnimationPanel`. */
export interface AnimTimeline {
  /** Scene this timeline belongs to. */
  sceneId: number;

  /** Index-ordered elements; lane order follows this order. */
  elements: AnimElement[];

  /** Manager-level state. */
  mgr: AnimMgrState;

  /**
   * Display-only frames-per-second for the ruler's frame readout and a
   * future render default. Not a C++ property; defaults to 30.
   */
  fps: number;
}

export interface HitTestResult {
    objtype: string;
    obj_id: number;
    obj_name: string;
    rend_id: number;
    rend_name: string;
    rendtype: string;
    atom_id: number;
    sel: string;
    message: string;
    x: number;
    y: number;
    z: number;
    occ: number;
    bfac: number;
    symm_id?: number;
    symm_name?: string;
}
