/**
 * @file types.ts
 * @description Shared TypeScript type definitions used across the application.
 *
 * All types in this module are pure data shapes (no logic or side-effects).
 * Importing from here instead of defining types inline in components keeps
 * the codebase consistent and makes cross-component data flows easy to trace.
 *
 * @module types
 */

import type { AppIconKey } from "@renderer/h3-kit/primitives";

// --- Scene / File-tree ---

/**
 * A single node in a generic tree view.
 *
 * The tree is recursive: each node may contain an arbitrary number of
 * child nodes, enabling multi-level hierarchies (e.g. Scene -> Object ->
 * Renderer, or Chain -> Residue -> Atom).
 */
export interface TreeNodeData {
  /** Stable, unique identifier for the node within its tree. */
  id: string;

  /** Human-readable display name shown in the tree row. */
  label: string;

  /** Semantic icon key rendered to the left of the label (see `AppIcon`). */
  icon: AppIconKey;

  /** Ordered list of child nodes. Empty array indicates a leaf node. */
  children: TreeNodeData[];

  /**
   * Optional secondary text shown to the right of the label (e.g. a
   * residue count, file size, or status indicator).
   */
  secondaryLabel?: string;
}

// --- Editor tabs ---

/**
 * Discriminator for tab types.
 *
 * | Type             | Rendered as                              |
 * |------------------|------------------------------------------|
 * | `"settings"`     | SettingsPane (application settings)      |
 * | `"molview"`      | MolViewPane (WebGL molecule view)        |
 *
 * When no tab is open, ContentPane shows the WelcomePane watermark as the
 * empty-state fallback (VSCode-like); that state is not a tab type.
 */
export type TabType = "settings" | "molview";

/**
 * Metadata for a single editor tab.
 */
export interface TabData {
  /** Stable, unique identifier generated at tab-creation time. */
  id: string;

  /** Label shown on the tab strip. */
  title: string;

  /** Semantic icon key for the tab label (see `AppIcon`). */
  icon: AppIconKey;

  /**
   * Discriminator for tab type.
   */
  type?: TabType;

  /**
   * CueMol view ID associated with this tab.
   * Present only for tabs with `type === "molview"`.
   */
  viewId?: number;

  /**
   * Scene the view belongs to. Present only for `type === "molview"`. Kept on
   * the tab so the active scene derives from the same record as the active
   * view, in the same render -- the two used to live in separate stores and
   * resolve one render apart.
   */
  sceneId?: number;
}

// --- Logging ---

/**
 * A single structured log entry displayed in `LogReplDraft` (a draft
 * REPL-enabled Output panel not yet wired into the app).
 *
 * Entries are created by `App.addLog` and are intentionally immutable
 * once appended to the log list.
 */
export interface LogEntry {
  /**
   * Timestamp string in `HH:MM:SS` format (local time, zero-padded).
   * Generated by `nowTimestamp()` in `App.tsx` at the moment the entry
   * is created.
   */
  time: string;

  /**
   * Severity level of the log message.
   *
   * | Level   | Intended use                          |
   * |---------|---------------------------------------|
   * | `INFO`  | Normal operational messages           |
   * | `WARN`  | Recoverable issues or deprecations    |
   * | `ERROR` | Failures that affect functionality    |
   * | `DEBUG` | Verbose diagnostics (dev only)        |
   */
  level: "INFO" | "WARN" | "ERROR" | "DEBUG";

  /** Human-readable description of the event. */
  msg: string;
}

// --- Boundary DTOs (re-exported) ---
//
// These describe data the WORKER produces. They live under `worker/shared/`
// so the ServiceMap slices there do not have to import back up into the
// renderer, and are re-exported here for the UI code that has always taken
// them from this module.

export type {
  AnimElementType,
  AnimAddType,
  AnimPlayState,
  AnimElement,
  AnimMgrState,
  AnimTimeline,
} from '@renderer/worker/shared/animTypes';
export type { HitTestResult } from '@renderer/worker/shared/hitTest';
