/**
 * @file types.ts
 * @description Shared TypeScript type definitions used across the application.
 *
 * All types in this module are pure data shapes (no logic or side-effects).
 * Importing from here instead of defining types inline in components keeps
 * the codebase consistent and makes cross-component data flows easy to trace.
 *
 * @module types
 */

// ────────────────────────────────────────────────────────────
// Scene / File-tree
// ────────────────────────────────────────────────────────────

/**
 * A single node in a generic tree displayed by `TreeView`.
 *
 * The tree is recursive: each node may contain an arbitrary number of
 * child nodes, enabling multi-level hierarchies (e.g. Scene → Object →
 * Renderer, or Chain → Residue → Atom).
 */
export interface TreeNodeData {
  /** Stable, unique identifier for the node within its tree. */
  id: string;

  /** Human-readable display name shown in the tree row. */
  label: string;

  /**
   * Blueprint icon name rendered to the left of the label.
   * Must be a valid `IconName` from `@blueprintjs/icons`.
   */
  icon: string;

  /** Ordered list of child nodes. Empty array indicates a leaf node. */
  children: TreeNodeData[];

  /**
   * Optional secondary text shown to the right of the label (e.g. a
   * residue count, file size, or status indicator).
   */
  secondaryLabel?: string;
}

// ────────────────────────────────────────────────────────────
// Editor tabs
// ────────────────────────────────────────────────────────────

import type { RenderResult } from "./data/renderResult";

/**
 * Discriminator for tab types.
 *
 * | Type             | Rendered as                              |
 * |------------------|------------------------------------------|
 * | `"welcome"`      | WelcomePane (start screen)               |
 * | `"settings"`     | SettingsPane (application settings)      |
 * | `"molview"`      | MolViewPane (WebGL molecule view)        |
 * | `"renderResult"` | RenderResultPane (completed render)      |
 */
export type TabType = "welcome" | "settings" | "molview" | "renderResult";

/**
 * Metadata for a single editor tab.
 */
export interface TabData {
  /** Stable, unique identifier generated at tab-creation time. */
  id: string;

  /** Label shown on the tab strip. */
  title: string;

  /**
   * Blueprint icon name for the tab label.
   */
  icon: string;

  /**
   * Discriminator for tab type.
   */
  type?: TabType;

  /**
   * CueMol view ID associated with this tab.
   * Present only for tabs with `type === "molview"`.
   */
  viewId?: number;

  /**
   * Completed render data.
   * Present only for tabs with `type === "renderResult"`.
   */
  renderResult?: RenderResult;
}

// ────────────────────────────────────────────────────────────
// Logging
// ────────────────────────────────────────────────────────────

/**
 * A single structured log entry displayed in `LogPanel`.
 *
 * Entries are created by `App.addLog` and are intentionally immutable
 * once appended to the log list.
 */
export interface LogEntry {
  /**
   * Timestamp string in `HH:MM:SS` format (local time, zero-padded).
   * Generated by `nowTimestamp()` in `App.tsx` at the moment the entry
   * is created.
   */
  time: string;

  /**
   * Severity level of the log message.
   *
   * | Level   | Intended use                          |
   * |---------|---------------------------------------|
   * | `INFO`  | Normal operational messages           |
   * | `WARN`  | Recoverable issues or deprecations    |
   * | `ERROR` | Failures that affect functionality    |
   * | `DEBUG` | Verbose diagnostics (dev only)        |
   */
  level: "INFO" | "WARN" | "ERROR" | "DEBUG";

  /** Human-readable description of the event. */
  msg: string;
}

// ────────────────────────────────────────────────────────────
// Sequence Alignment (MSA)
// ────────────────────────────────────────────────────────────

/**
 * A single entry (row) in a multiple sequence alignment.
 *
 * Each entry represents one chain or sequence that participates in the
 * alignment. The `sequence` field contains the aligned string, including
 * gap characters ('-') to maintain column correspondence.
 */
export interface AlignmentEntry {
  /** Stable, unique identifier for this alignment row. */
  id: string;

  /**
   * Display label shown in the left column (e.g. "A:P34897_0_poc",
   * "B:5v7i"). Typically formatted as "Chain:Source".
   */
  label: string;

  /**
   * Aligned sequence string using one-letter amino acid codes.
   * Gap characters ('-') indicate insertions/deletions.
   * All entries in the same alignment must have identical length.
   */
  sequence: string;
}

/**
 * Complete alignment data for the MSA viewer.
 *
 * Contains metadata about the alignment (name, start position)
 * and an ordered list of aligned sequence entries.
 */
export interface AlignmentData {
  /** Human-readable name for this alignment set. */
  name: string;

  /**
   * Starting residue position of the alignment (1-based).
   * Used to render position numbers on the ruler.
   */
  startPosition: number;

  /** Ordered list of aligned sequence entries (rows). */
  entries: AlignmentEntry[];
}

// ────────────────────────────────────────────────────────────
// Animation Timeline
// ────────────────────────────────────────────────────────────

/**
 * A single keyframe in an animation track.
 *
 * Keyframes mark specific frames where a property value is explicitly
 * defined. Values between keyframes are interpolated.
 */
export interface Keyframe {
  /** Frame number (0-based). */
  frame: number;

  /**
   * Property value at this frame.
   * Stored as a string for display; actual interpolation is handled
   * by the animation engine on the backend.
   */
  value: string;

  /** Whether this keyframe is currently selected in the UI. */
  selected?: boolean;
}

/**
 * A single animation track representing a property's change over time.
 *
 * Each track corresponds to one animatable property (e.g. camera position,
 * object opacity, light intensity) and contains an ordered set of keyframes.
 */
export interface AnimationTrack {
  /** Stable, unique identifier for this track. */
  id: string;

  /** Display label shown in the track list (e.g. "Camera Position"). */
  label: string;

  /** Blueprint icon name for the track label. */
  icon?: string;

  /** Ordered list of keyframes in this track. */
  keyframes: Keyframe[];
}

/**
 * Complete animation data for the timeline panel.
 *
 * Contains global timing parameters and an ordered list of property tracks.
 */
export interface AnimationData {
  /** Human-readable name of the animation (e.g. "rotation_anim"). */
  name: string;

  /** Total number of frames in the animation. */
  totalFrames: number;

  /** Playback frames per second. */
  fps: number;

  /** Ordered list of animation tracks. */
  tracks: AnimationTrack[];
}

export interface HitTestResult {
    objtype: string;
    obj_id: number;
    obj_name: string;
    rend_id: number;
    rend_name: string;
    rendtype: string;
    atom_id: number;
    sel: string;
    message: string;
    x: number;
    y: number;
    z: number;
    occ: number;
    bfac: number;
    symm_id?: number;
    symm_name?: string;
}
