export { ActivityBar } from "./ActivityBar";
export type { ActivityView } from "./ActivityBar";
export { Toolbar } from "./Toolbar";
export { SidePanel } from "./SidePanel";
export { ContentArea } from "./ContentArea";
export { TabBar } from "./TabBar";
export { ContentPane } from "./ContentPane";
export { SettingsPane } from "./SettingsPane";
export { WelcomePane } from "./WelcomePane";
export { CodeViewPane } from "./CodeViewPane";
export { MolViewPane } from "./MolViewPane";
export { LogPanel } from "./LogPanel";
export { StatusBar } from "./StatusBar";
//export { ColorPanel } from "./ColorPanel";
export { InspectorPanel } from "./InspectorPanel";
