/**
 * Pin the UXP-syntax selection-string generated by `selStrFromTree`.
 *
 * Mirrors `panel.makeSelstrByTreeSel` / `panel.makeSelstrByNode` in
 * `uxp_gui/cuemol2/base/content/molstruct-panel.js` for the chain branch
 * (Phase 1 scope). Residue / atom encodings are also pinned through
 * the decoder so the wire format is locked while we add Phase 2 lazy
 * loading.
 */

import { describe, it, expect } from 'vitest'
import {
    encodeChainId,
    selStrFromTree,
    decodeMolTreeId,
    type MolTreeId,
} from '../components/panes/molStruct/selStrFromTree'

function set(...ids: MolTreeId[]): Set<MolTreeId> {
    return new Set(ids)
}

describe('selStrFromTree — chain rows (Phase 1)', () => {
    it('returns empty string for an empty selection', () => {
        expect(selStrFromTree(set())).toBe('')
    })

    it('encodes a single chain as UXP "c;\'A\'"', () => {
        expect(selStrFromTree(set(encodeChainId('A')))).toBe("c;'A'")
    })

    it('joins multiple chains with " | "', () => {
        // Sets preserve insertion order; we rely on that to keep the
        // joined string deterministic.
        const result = selStrFromTree(set(encodeChainId('A'), encodeChainId('B')))
        expect(result).toBe("c;'A' | c;'B'")
    })

    it('survives multi-char chain names (e.g. "AAA")', () => {
        expect(selStrFromTree(set(encodeChainId('AAA')))).toBe("c;'AAA'")
    })

    it('drops undecodable ids defensively', () => {
        const result = selStrFromTree(set('garbage', encodeChainId('A'), ''))
        expect(result).toBe("c;'A'")
    })
})

describe('decodeMolTreeId — forward-compat wire format', () => {
    it('decodes chain ids', () => {
        expect(decodeMolTreeId('chain:A')).toEqual({ kind: 'chain', chain: 'A' })
    })

    it('decodes residue ids (Phase 2 wire form)', () => {
        expect(decodeMolTreeId('resid:A:10')).toEqual({
            kind: 'resid',
            chain: 'A',
            index: 10,
        })
    })

    it('decodes atom ids (Phase 2 wire form)', () => {
        expect(decodeMolTreeId('atom:A:10:123')).toEqual({
            kind: 'atom',
            chain: 'A',
            index: 10,
            atomId: 123,
        })
    })

    it('returns null for malformed ids', () => {
        expect(decodeMolTreeId('')).toBeNull()
        expect(decodeMolTreeId('chain:')).toBeNull()
        expect(decodeMolTreeId('resid:A:bad')).toBeNull()
        expect(decodeMolTreeId('atom:A:10')).toBeNull()
    })
})

describe('selStrFromTree — residue / atom rows (Phase 2 wire pin)', () => {
    it('encodes a single residue', () => {
        expect(selStrFromTree(set('resid:A:10'))).toBe("'A'.10.*")
    })

    it('encodes a single atom by atom id', () => {
        expect(selStrFromTree(set('atom:A:10:123'))).toBe('aid 123')
    })

    it('joins mixed chain + residue + atom rows', () => {
        const result = selStrFromTree(set('chain:A', 'resid:B:5', 'atom:C:7:42'))
        expect(result).toBe("c;'A' | 'B'.5.* | aid 42")
    })
})
