/**
 * Pin the UXP-syntax selection-string generated by `selStrFromTree`.
 *
 * Mirrors `panel.makeSelstrByTreeSel` / `panel.makeSelstrByNode` in
 * `uxp_gui/cuemol2/base/content/molstruct-panel.js` for the chain branch
 * Residue / atom encodings are also pinned through
 * the decoder so the wire format is locked for the lazy
 * loading.
 */

import { describe, it, expect } from 'vitest'
import {
    encodeChainId,
    encodeResidueId,
    encodeAtomId,
    selStrFromTree,
    decodeMolTreeId,
    type MolTreeId,
} from '../components/panes/molStruct/selStrFromTree'

function set(...ids: MolTreeId[]): Set<MolTreeId> {
    return new Set(ids)
}

describe('selStrFromTree — chain rows', () => {
    it('returns empty string for an empty selection', () => {
        expect(selStrFromTree(set())).toBe('')
    })

    it('encodes a single chain as UXP "c;\'A\'"', () => {
        expect(selStrFromTree(set(encodeChainId('A')))).toBe("c;'A'")
    })

    it('joins multiple chains with " | "', () => {
        // Sets preserve insertion order; we rely on that to keep the
        // joined string deterministic.
        const result = selStrFromTree(set(encodeChainId('A'), encodeChainId('B')))
        expect(result).toBe("c;'A' | c;'B'")
    })

    it('survives multi-char chain names (e.g. "AAA")', () => {
        expect(selStrFromTree(set(encodeChainId('AAA')))).toBe("c;'AAA'")
    })

    it('drops undecodable ids defensively', () => {
        const result = selStrFromTree(set('garbage', encodeChainId('A'), ''))
        expect(result).toBe("c;'A'")
    })
})

describe('decodeMolTreeId — wire format', () => {
    it('decodes chain ids', () => {
        expect(decodeMolTreeId('chain:A')).toEqual({ kind: 'chain', chain: 'A' })
    })

    it('decodes residue ids (index kept as string for insertion codes)', () => {
        expect(decodeMolTreeId('resid:A:10')).toEqual({
            kind: 'resid',
            chain: 'A',
            index: '10',
        })
        expect(decodeMolTreeId('resid:A:10A')).toEqual({
            kind: 'resid',
            chain: 'A',
            index: '10A',
        })
    })

    it('decodes atom ids (index string + numeric atomId)', () => {
        expect(decodeMolTreeId('atom:A:10:123')).toEqual({
            kind: 'atom',
            chain: 'A',
            index: '10',
            atomId: 123,
        })
        expect(decodeMolTreeId('atom:B:10A:99')).toEqual({
            kind: 'atom',
            chain: 'B',
            index: '10A',
            atomId: 99,
        })
    })

    it('returns null for malformed ids', () => {
        expect(decodeMolTreeId('')).toBeNull()
        expect(decodeMolTreeId('chain:')).toBeNull()
        expect(decodeMolTreeId('atom:A:10')).toBeNull()
        // atom-id slice must parse as a number
        expect(decodeMolTreeId('atom:A:10:abc')).toBeNull()
    })
})

describe('selStrFromTree — residue / atom rows', () => {
    it('encodes a single residue', () => {
        expect(selStrFromTree(set(encodeResidueId('A', '10')))).toBe("'A'.10.*")
    })

    it('preserves residue index strings (insertion codes)', () => {
        expect(selStrFromTree(set(encodeResidueId('A', '10A')))).toBe("'A'.10A.*")
    })

    it('encodes a single atom by atom id', () => {
        expect(selStrFromTree(set(encodeAtomId('A', '10', 123)))).toBe('aid 123')
    })

    it('joins mixed chain + residue + atom rows across chains', () => {
        const result = selStrFromTree(
            set(encodeChainId('A'), encodeResidueId('B', '5'), encodeAtomId('C', '7', 42)),
        )
        expect(result).toBe("c;'A' | 'B'.5.* | aid 42")
    })

    it('drops residues / atoms when their chain row is also selected', () => {
        // UXP "chain selection subsumes children" parity.
        const result = selStrFromTree(
            set(encodeChainId('A'), encodeResidueId('A', '5'), encodeAtomId('A', '5', 99)),
        )
        expect(result).toBe("c;'A'")
    })
})

describe('selStrFromTree — residue range merging', () => {
    function order(...indices: string[]): ReadonlyMap<string, readonly string[]> {
        return new Map([['A', indices]])
    }

    it('merges three positionally-adjacent residues into one range', () => {
        const result = selStrFromTree(
            set(
                encodeResidueId('A', '10'),
                encodeResidueId('A', '11'),
                encodeResidueId('A', '12'),
            ),
            order('10', '11', '12', '13'),
        )
        expect(result).toBe("'A'.10:12.*")
    })

    it('splits non-adjacent residues into separate segments', () => {
        const result = selStrFromTree(
            set(
                encodeResidueId('A', '10'),
                encodeResidueId('A', '11'),
                encodeResidueId('A', '13'),
            ),
            order('10', '11', '12', '13'),
        )
        expect(result).toBe("'A'.10:11.* | 'A'.13.*")
    })

    it('treats insertion-coded residues as adjacent when positionally next', () => {
        const result = selStrFromTree(
            set(encodeResidueId('A', '10'), encodeResidueId('A', '10A')),
            order('10', '10A', '11'),
        )
        expect(result).toBe("'A'.10:10A.*")
    })

    it('without residueOrder, falls back to per-residue segments (no merging)', () => {
        const result = selStrFromTree(
            set(encodeResidueId('A', '10'), encodeResidueId('A', '11')),
        )
        expect(result).toBe("'A'.10.* | 'A'.11.*")
    })
})
