name: 'Download deplibs posix'
description: 'Download deplibs posix'

inputs:
  basedir:
     description: 'base dir'
     required: true

runs:
  using: "composite"
  steps:

  - name: Download deplibs
    shell: bash
    run: |
      if [[ "$RUNNER_OS" == "Windows" ]]; then
        GITHUB_WORKSPACE=$(cygpath -u "$GITHUB_WORKSPACE")
        BASEDIR=$(cygpath -u "${{ inputs.basedir }}")
      else
        BASEDIR=${{ inputs.basedir }}
      fi

      cd ${GITHUB_WORKSPACE}
      bash build_scripts/download_deplibs/run.sh $BASEDIR ${{ runner.os }} ${{ runner.arch }}

  - name: Download python-build-standalone (macOS)
    if: ${{ runner.os == 'macOS' && env.EMBED_PYTHON != '' }}
    shell: bash
    run: |
      echo "Download python-build-standalone $EMBED_PYTHON"
      BASEDIR=${{ inputs.basedir }}
      cd $BASEDIR

      URL_BASE="https://github.com/astral-sh/python-build-standalone/releases/download"
      DATE="20251217"
      ARCH="aarch64"
      OS="apple-darwin"
      PYTHON_VER="3.12.12"
      TGZ_FILE="cpython-${PYTHON_VER}+${DATE}-${ARCH}-${OS}-install_only_stripped.tar.gz"
      URL="${URL_BASE}/${DATE}/${TGZ_FILE}"
      curl -sS -L -O $URL
      tar xjf $TGZ_FILE
      
      rm $TGZ_FILE
      echo "PYTHON_ROOT=$BASEDIR/python" >> $GITHUB_ENV
      ls -la
