name: 'Download deplibs posix'
description: 'Download deplibs posix'

inputs:
  basedir:
     description: 'base dir'
     required: true

runs:
  using: "composite"
  steps:

  - name: Download deplibs
    shell: bash
    run: |
      if [[ "$RUNNER_OS" == "Windows" ]]; then
        GITHUB_WORKSPACE=$(cygpath -u "$GITHUB_WORKSPACE")
        BASEDIR=$(cygpath -u "${{ inputs.basedir }}")
      else
        BASEDIR=${{ inputs.basedir }}
      fi

      cd ${GITHUB_WORKSPACE}
      bash build_scripts/download_deplibs/run.sh $BASEDIR ${{ runner.os }} ${{ runner.arch }}

  - name: Download python-build-standalone (macOS)
    if: ${{ runner.os == 'macOS' && env.EMBED_PYTHON != "" }}
    shell: bash
    run: |
      echo "Download python-build-standalone $EMBED_PYTHON"
