#line 2 "../../src/gfx/color_scanner.cxx"

#line 4 "../../src/gfx/color_scanner.cxx"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer col_create_buffer
#define yy_delete_buffer col_delete_buffer
#define yy_flex_debug col_flex_debug
#define yy_init_buffer col_init_buffer
#define yy_flush_buffer col_flush_buffer
#define yy_load_buffer_state col_load_buffer_state
#define yy_switch_to_buffer col_switch_to_buffer
#define yyin colin
#define yyleng colleng
#define yylex collex
#define yylineno collineno
#define yyout colout
#define yyrestart colrestart
#define yytext coltext
#define yywrap colwrap
#define yyalloc colalloc
#define yyrealloc colrealloc
#define yyfree colfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE colrestart(colin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t colleng;

extern FILE *colin, *colout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up coltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up coltext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via colrestart()), so that the user can continue scanning by
	 * just pointing colin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when coltext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t colleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow colwrap()'s to do buffer switches
 * instead of setting up a fresh colin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void colrestart (FILE *input_file  );
void col_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE col_create_buffer (FILE *file,int size  );
void col_delete_buffer (YY_BUFFER_STATE b  );
void col_flush_buffer (YY_BUFFER_STATE b  );
void colpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void colpop_buffer_state (void );

static void colensure_buffer_stack (void );
static void col_load_buffer_state (void );
static void col_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER col_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE col_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE col_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE col_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *colalloc (yy_size_t  );
void *colrealloc (void *,yy_size_t  );
void colfree (void *  );

#define yy_new_buffer col_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        colensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            col_create_buffer(colin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        colensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            col_create_buffer(colin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define colwrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *colin = (FILE *) 0, *colout = (FILE *) 0;

typedef int yy_state_type;

extern int collineno;

int collineno = 1;

extern char *coltext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr coltext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up coltext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	colleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 40
#define YY_END_OF_BUFFER 41
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[105] =
    {   0,
        0,    0,    0,    0,    0,    0,   41,   38,    1,    3,
       38,   38,    5,    6,   38,   11,   38,   32,   32,    9,
       10,   36,   36,   36,   38,   36,   36,    7,    8,   39,
        2,    4,   39,   12,   39,   39,   20,   20,   15,   20,
       14,   40,   13,    1,    0,    0,    0,   32,   32,   30,
       31,   36,   36,   36,   32,   36,   36,   37,   36,   36,
        2,    0,    0,    0,    0,   16,   17,   20,   20,   20,
       20,    0,    0,    0,   32,    0,   33,   26,   22,   25,
       21,    0,    0,    0,    0,   18,   34,    0,    0,   30,
       28,   24,   27,   23,   19,    0,   16,    0,    0,    0,

        0,   35,   29,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    5,    6,    1,    7,    8,
        9,    1,   10,   11,   10,   12,    1,   13,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,    1,
        1,    1,    1,    1,   17,   18,   19,   19,   20,   19,
       21,   22,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   24,   25,   23,   23,   23,   23,   23,   23,   23,
        1,   26,    1,    1,   23,    1,   27,   28,   29,   19,

       20,   19,   30,   31,   23,   23,   23,   32,   33,   23,
       34,   23,   23,   35,   36,   23,   23,   23,   23,   37,
       23,   23,   38,    1,   39,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[40] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    1,    1,    3,
        1,    3,    4,    4,    1,    1,    4,    4,    4,    4,
        3,    3,    3,    3,    3,    1,    4,    4,    4,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[118] =
    {   0,
        0,    0,   39,    0,   76,   77,  285,  286,  282,  286,
        0,  250,  286,  286,   73,  286,   68,   82,   85,  286,
      286,   94,   95,   96,    0,   97,   98,  286,  286,  286,
      280,  286,    0,  286,   99,   76,  109,  112,  286,  123,
      286,  286,  286,  279,    0,  242,   79,  124,  128,  130,
      286,  133,  141,  150,  145,  154,  168,  286,  159,  169,
      264,    0,  118,  170,  179,  175,  286,  184,  188,  197,
      192,    0,  233,  206,  215,  220,    0,  225,  226,  229,
      233,    0,  234,  238,  244,    0,    0,  235,  135,  194,
      243,  247,  255,  256,  286,  199,  209,    0,  229,    0,

      208,  286,  286,  286,  268,  232,  270,  274,  195,  276,
      169,  157,  148,  123,  112,  110,  101
    } ;

static yyconst flex_int16_t yy_def[118] =
    {   0,
      104,    1,  104,    3,  105,  105,  104,  104,  104,  104,
      106,  104,  104,  104,  104,  104,  104,  107,  107,  104,
      104,  107,  107,  107,  108,  107,  107,  104,  104,  104,
      104,  104,  109,  104,  104,  104,  110,  110,  104,  110,
      104,  104,  104,  104,  111,  104,  104,  104,  104,  104,
      104,  107,  107,  107,  107,  107,  107,  104,  107,  107,
      104,  112,  104,  104,  104,  104,  104,  110,  110,  110,
      110,  113,  104,  104,  104,  104,   54,  107,  107,  107,
      107,  114,  104,  104,  104,   70,  115,  104,  104,  104,
      107,  107,  107,  107,  104,  104,  104,  116,  104,  117,

      104,  104,  104,    0,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104
    } ;

static yyconst flex_uint16_t yy_nxt[326] =
    {   0,
        8,    9,   10,   11,   12,    8,    8,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   22,   22,   22,
       22,   23,   22,   24,   22,   25,   22,   22,   22,   22,
       26,   22,   22,   22,   27,   22,   22,   28,   29,   30,
       31,   32,   33,   30,   30,   34,   30,   30,   35,   30,
       36,   37,   38,   30,   39,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   30,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   30,   30,   42,   42,
       50,   50,   43,   43,   47,   48,   49,   51,   66,   66,
       51,   50,   50,   47,   53,   53,   47,   55,   55,  104,

      104,  104,  104,  104,  102,  104,  104,  104,  104,  104,
       63,   64,   65,  100,   67,   98,   57,   67,   54,   56,
       63,   69,   69,   63,   71,   71,   95,   60,  104,   51,
       66,   66,   59,   51,  104,   47,   74,   74,  104,   47,
       75,   75,   50,   50,  104,   70,  104,   90,   90,   76,
       51,   87,   47,   53,   53,  104,   47,   55,   55,  104,
       82,  104,   77,   77,  104,  104,   77,   77,   77,   77,
      104,   78,   72,  104,  104,   67,   77,   77,   77,  104,
      104,   63,   83,   83,   67,   79,   80,   66,   66,  104,
       63,   84,   84,  104,   85,  104,   81,   67,   62,   63,

       69,   69,  104,   63,   71,   71,   90,   90,  104,   86,
       86,   97,   97,   86,   86,   86,   86,   47,   74,   74,
       51,   97,   97,   86,   86,   86,   47,   75,   75,   89,
      104,  104,   90,   90,  104,   45,  104,  104,  104,  103,
      104,   91,   92,   67,  104,   63,   83,   83,  104,   63,
       84,   84,  104,   96,  104,   93,   97,   97,  104,   94,
      104,  104,  101,   99,   88,   61,  104,  104,   41,   41,
       41,   41,   52,   52,   58,   73,   58,   58,   68,   68,
       44,   61,   46,   44,  104,    7,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,

      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104
    } ;

static yyconst flex_int16_t yy_chk[326] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    5,    6,
       17,   17,    5,    6,   15,   15,   15,   18,   36,   36,
       19,   47,   47,   18,   18,   18,   19,   19,   19,   22,

       23,   24,   26,   27,  117,   22,   23,   24,   26,   27,
       35,   35,   35,  116,   37,  115,   24,   38,   18,   23,
       37,   37,   37,   38,   38,   38,  114,   27,   40,   48,
       63,   63,   26,   49,   40,   48,   48,   48,   52,   49,
       49,   49,   50,   50,   52,   37,   53,   89,   89,   50,
       55,  113,   53,   53,   53,   54,   55,   55,   55,   56,
      112,   54,   54,   54,   59,   56,   54,   54,   54,   54,
       59,   56,  111,   57,   60,   64,   54,   54,   54,   57,
       60,   64,   64,   64,   65,   57,   59,   66,   66,   68,
       65,   65,   65,   69,   66,   68,   60,   71,  109,   69,

       69,   69,   70,   71,   71,   71,   90,   90,   70,   70,
       70,   96,   96,   70,   70,   70,   70,   74,   74,   74,
       75,   97,   97,   70,   70,   70,   75,   75,   75,   76,
       78,   79,   76,   76,   80,  106,   78,   79,   81,  101,
       80,   78,   79,   84,   81,   83,   83,   83,   91,   84,
       84,   84,   92,   85,   91,   80,   85,   85,   92,   81,
       93,   94,   99,   88,   73,   61,   93,   94,  105,  105,
      105,  105,  107,  107,  108,   46,  108,  108,  110,  110,
       44,   31,   12,    9,    7,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,

      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int col_flex_debug;
int col_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *coltext;
#line 1 "../../src/gfx/color_scanner.lxx"
/*
 *  Color description scanner
 */

#line 11 "../../src/gfx/color_scanner.lxx"
#include <common.h>
#include <qlib/LChar.hpp>
#include <qlib/LString.hpp>

#include "ColCompiler.hpp"

using namespace gfx;

using qlib::LChar;
using qlib::LString;

#include "color_parser.h"


#undef YY_INPUT
#define YY_INPUT(buf,result,max) (result = ColCompiler::getInstance()->feedInput(buf, max))

extern int colerror(char* error);

#line 620 "../../src/gfx/color_scanner.cxx"

#define INITIAL 0
#define MODIFVAL_STATE 1
#define SQ_STRING 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int collex_destroy (void );

int colget_debug (void );

void colset_debug (int debug_flag  );

YY_EXTRA_TYPE colget_extra (void );

void colset_extra (YY_EXTRA_TYPE user_defined  );

FILE *colget_in (void );

void colset_in  (FILE * _in_str  );

FILE *colget_out (void );

void colset_out  (FILE * _out_str  );

yy_size_t colget_leng (void );

char *colget_text (void );

int colget_lineno (void );

void colset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int colwrap (void );
#else
extern int colwrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( coltext, colleng, 1, colout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( colin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( colin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, colin))==0 && ferror(colin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(colin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int collex (void);

#define YY_DECL int collex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after coltext and colleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! colin )
			colin = stdin;

		if ( ! colout )
			colout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			colensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				col_create_buffer(colin,YY_BUF_SIZE );
		}

		col_load_buffer_state( );
		}

	{
#line 43 "../../src/gfx/color_scanner.lxx"



  LString qstring_buf;


 /*
  *  Color tokens
  */

 /* Ignore white spaces */
#line 852 "../../src/gfx/color_scanner.cxx"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of coltext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 105 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 104 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
#line 55 "../../src/gfx/color_scanner.lxx"
case 2:
#line 56 "../../src/gfx/color_scanner.lxx"
case 3:
/* rule 3 can match eol */
#line 57 "../../src/gfx/color_scanner.lxx"
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 57 "../../src/gfx/color_scanner.lxx"
{ ; }
	YY_BREAK
/* Operators */
case 5:
YY_RULE_SETUP
#line 61 "../../src/gfx/color_scanner.lxx"
{ return COL_LPAREN; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "../../src/gfx/color_scanner.lxx"
{ return COL_RPAREN; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 64 "../../src/gfx/color_scanner.lxx"
{ return COL_LBRACE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 65 "../../src/gfx/color_scanner.lxx"
{ return COL_RBRACE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 67 "../../src/gfx/color_scanner.lxx"
{ return COL_COLON; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 68 "../../src/gfx/color_scanner.lxx"
{ return COL_SEMICOLON; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 69 "../../src/gfx/color_scanner.lxx"
{ return COL_COMMA; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 71 "../../src/gfx/color_scanner.lxx"
{
  qstring_buf = LString();
  BEGIN SQ_STRING;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 75 "../../src/gfx/color_scanner.lxx"
{ 
  BEGIN MODIFVAL_STATE;
  // MB_DPRINTLN("ColModifVal %s", qstring_buf.c_str());
  collval.str = LChar::dup(qstring_buf.c_str());
  return COL_MODIFVAL;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 81 "../../src/gfx/color_scanner.lxx"
{
  qstring_buf += coltext;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 85 "../../src/gfx/color_scanner.lxx"
{ return COL_SEMICOLON; }
	YY_BREAK
case 16:
#line 87 "../../src/gfx/color_scanner.lxx"
case 17:
#line 88 "../../src/gfx/color_scanner.lxx"
case 18:
#line 89 "../../src/gfx/color_scanner.lxx"
case 19:
#line 90 "../../src/gfx/color_scanner.lxx"
case 20:
YY_RULE_SETUP
#line 90 "../../src/gfx/color_scanner.lxx"
{
  // MB_DPRINTLN("ColModifVal %s", coltext);
  collval.str = LChar::dup(coltext);
  return COL_MODIFVAL;
}
	YY_BREAK
/* Reserved keywords */
case 21:
YY_RULE_SETUP
#line 98 "../../src/gfx/color_scanner.lxx"
{ return COL_RGB; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 99 "../../src/gfx/color_scanner.lxx"
{ return COL_RGB; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 101 "../../src/gfx/color_scanner.lxx"
{ return COL_RGBA; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 102 "../../src/gfx/color_scanner.lxx"
{ return COL_RGBA; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 104 "../../src/gfx/color_scanner.lxx"
{ return COL_HSB; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 105 "../../src/gfx/color_scanner.lxx"
{ return COL_HSB; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 107 "../../src/gfx/color_scanner.lxx"
{ return COL_HSBA; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 108 "../../src/gfx/color_scanner.lxx"
{ return COL_HSBA; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 110 "../../src/gfx/color_scanner.lxx"
{ return COL_MOLCOL; }
	YY_BREAK
/* Values */
case 30:
YY_RULE_SETUP
#line 113 "../../src/gfx/color_scanner.lxx"
{
  // MB_DPRINTLN("ColFloatNum %s", coltext);
  LChar::toDouble(coltext, collval.floatnum);
  return COL_FLOATNUM;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 118 "../../src/gfx/color_scanner.lxx"
{
  // MB_DPRINTLN("ColPercNum %s", coltext);
  int nlen = LChar::length(coltext);
  coltext[nlen-1] = '\0';
  LChar::toDouble(coltext, collval.floatnum);
  return COL_PERCENTNUM;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 125 "../../src/gfx/color_scanner.lxx"
{
  // MB_DPRINTLN("ColIntNum %s", coltext);
  LChar::toDouble(coltext, collval.floatnum);
  return COL_FLOATNUM;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 130 "../../src/gfx/color_scanner.lxx"
{
  // MB_DPRINTLN("ColHexNum %s", coltext);
  LChar::toInt(coltext, collval.intnum);
  return COL_INTNUM;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 136 "../../src/gfx/color_scanner.lxx"
{
  // MB_DPRINTLN("ColHTML_3 %s", coltext);
  char sbuf[3];  
  int r, g, b;
  sbuf[2] = 0;

  sbuf[0] = sbuf[1] = coltext[1];
  LChar::toInt(sbuf, r, 16);

  sbuf[0] = sbuf[1] = coltext[2];
  LChar::toInt(sbuf, g, 16);

  sbuf[0] = sbuf[1] = coltext[3];
  LChar::toInt(sbuf, b, 16);

  collval.intnum = ((r & 0xFF) << 16) | ((g & 0xFF) << 8) | ((b & 0xFF) << 0);
  return COL_HTML3;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 155 "../../src/gfx/color_scanner.lxx"
{
  // MB_DPRINTLN("ColHTML_6 %s", coltext);
  char sbuf[3];  
  int r, g, b;
  sbuf[2] = 0;

  sbuf[0] = coltext[1];
  sbuf[1] = coltext[2];
  LChar::toInt(sbuf, r, 16);

  sbuf[0] = coltext[3];
  sbuf[1] = coltext[4];
  LChar::toInt(sbuf, g, 16);

  sbuf[0] = coltext[5];
  sbuf[1] = coltext[6];
  LChar::toInt(sbuf, b, 16);

  collval.intnum = ((r & 0xFF) << 16) | ((g & 0xFF) << 8) | ((b & 0xFF) << 0);
  return COL_HTML6;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 177 "../../src/gfx/color_scanner.lxx"
{
  // MB_DPRINTLN("ColName %s", coltext);
  collval.str = LChar::dup(coltext);
  return COL_NAME;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 183 "../../src/gfx/color_scanner.lxx"
{
  colerror("unknown character(s) in color definition");
  return LEX_ERROR;
}
	YY_BREAK
case 38:
#line 189 "../../src/gfx/color_scanner.lxx"
case 39:
YY_RULE_SETUP
#line 189 "../../src/gfx/color_scanner.lxx"
{
  colerror("unknown character(s) in color definition");
  return LEX_ERROR;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 194 "../../src/gfx/color_scanner.lxx"
ECHO;
	YY_BREAK
#line 1165 "../../src/gfx/color_scanner.cxx"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(MODIFVAL_STATE):
case YY_STATE_EOF(SQ_STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed colin at a new source and called
			 * collex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = colin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( colwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * coltext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of collex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					colrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			colrestart(colin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((int) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) colrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 105 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 105 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 104);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up coltext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					colrestart(colin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( colwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve coltext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void colrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        colensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            col_create_buffer(colin,YY_BUF_SIZE );
	}

	col_init_buffer(YY_CURRENT_BUFFER,input_file );
	col_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void col_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		colpop_buffer_state();
	 *		colpush_buffer_state(new_buffer);
     */
	colensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	col_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (colwrap()) processing, but the only time this flag
	 * is looked at is after colwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void col_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	colin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE col_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) colalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in col_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) colalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in col_create_buffer()" );

	b->yy_is_our_buffer = 1;

	col_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with col_create_buffer()
 * 
 */
    void col_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		colfree((void *) b->yy_ch_buf  );

	colfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a colrestart() or at EOF.
 */
    static void col_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	col_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then col_init_buffer was _probably_
     * called from colrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void col_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		col_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void colpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	colensure_buffer_stack();

	/* This block is copied from col_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from col_switch_to_buffer. */
	col_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void colpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	col_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		col_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void colensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)colalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in colensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)colrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in colensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE col_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) colalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in col_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	col_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to collex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       col_scan_bytes() instead.
 */
YY_BUFFER_STATE col_scan_string (yyconst char * yystr )
{
    
	return col_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to collex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE col_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) colalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in col_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = col_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in col_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up coltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		coltext[colleng] = (yy_hold_char); \
		(yy_c_buf_p) = coltext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		colleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int colget_lineno  (void)
{
        
    return collineno;
}

/** Get the input stream.
 * 
 */
FILE *colget_in  (void)
{
        return colin;
}

/** Get the output stream.
 * 
 */
FILE *colget_out  (void)
{
        return colout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t colget_leng  (void)
{
        return colleng;
}

/** Get the current token.
 * 
 */

char *colget_text  (void)
{
        return coltext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void colset_lineno (int  _line_number )
{
    
    collineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see col_switch_to_buffer
 */
void colset_in (FILE *  _in_str )
{
        colin = _in_str ;
}

void colset_out (FILE *  _out_str )
{
        colout = _out_str ;
}

int colget_debug  (void)
{
        return col_flex_debug;
}

void colset_debug (int  _bdebug )
{
        col_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from collex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    colin = stdin;
    colout = stdout;
#else
    colin = (FILE *) 0;
    colout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * collex_init()
     */
    return 0;
}

/* collex_destroy is for both reentrant and non-reentrant scanners. */
int collex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		col_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		colpop_buffer_state();
	}

	/* Destroy the stack itself. */
	colfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * collex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *colalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *colrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void colfree (void * ptr )
{
			free( (char *) ptr );	/* see colrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 194 "../../src/gfx/color_scanner.lxx"



//private static
void ColCompiler::resetScannerState()
{
  BEGIN INITIAL;
  colrestart(NULL);
}

/////

//static 
void ColCompiler::setModifState()
{
  BEGIN MODIFVAL_STATE;
}

//static
void ColCompiler::setInitState()
{
  BEGIN INITIAL;
}

