name: 'Build python module posix'
description: 'Build python module posix'

inputs:
  basedir:
     description: 'base dir'
     required: true

runs:
  using: "composite"
  steps:

  - name: Create Python virtual environment
    shell: bash
    run: |
      cd ${GITHUB_WORKSPACE}
      python3 -m venv .venv

  - name: Build and install python module
    shell: bash
    env:
      SCCACHE_GHA_ENABLED: "true"
      PYTHON: python
    run: |
      cd ${GITHUB_WORKSPACE}
      bash build_scripts/build_pymod_posix/run.sh ${{ inputs.basedir }}
