name: Build and release

on:
  push:
#    branches-ignore:
#      - '**'

    branches:
      - '**'  # All branches
    tags:
      - 'v*'  # Release tags (v1.0.0, etc)
  pull_request:
  workflow_dispatch:

env:
  mozbuild-cache-version: v1

  BUILD_MODE: ${{ 
    (github.ref == 'refs/heads/develop' || 
     github.event_name == 'workflow_dispatch' || 
     startsWith(github.ref, 'refs/tags/')) && 'full' || 'quick' 
  }}

###############################################

jobs:
  build_posix:
    name: '${{ matrix.name }}'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-15
            name: "MacOS 15 arm64 clang"
          - os: macos-15-intel
            name: "MacOS 15 x64 clang"
          # - os: macos-14
          #   name: "MacOS 14 arm64 clang"
          # - os: macos-13
          #   name: "MacOS 13 x64 clang"

    env:
      MACOSX_DEPLOYMENT_TARGET: "10.15"

    steps:
    - name: Show build mode
      run: |
        echo "BUILD_MODE: ${{ env.BUILD_MODE }}"
        echo "Branch/Tag: ${{ github.ref }}"
        echo "Event: ${{ github.event_name }}"

    - uses: actions/checkout@v4

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.9

    - name: Show build env versions
      shell: bash
      run: |
        echo "RUNNER_TYPE=${{ matrix.os }}" >> $GITHUB_ENV
        set -eux
        clang --version
        xcodebuild -version
        ninja --version

    - name: Download deplibs
      uses: ./build_scripts/download_deplibs
      with:
        basedir: ${{ github.workspace }}/target

    - name: Build libcuemol2
      uses: ./build_scripts/build_libcuemol2_posix
      with:
        basedir: ${{ github.workspace }}/target

    - name: Build and check cuetty
      uses: ./build_scripts/build_cuetty_posix
      with:
        basedir: ${{ github.workspace }}/target

    - name: Check cuetty run
      shell: bash
      run: |
        set -eux
        BASEDIR=${{ github.workspace }}/target
        ls -la $BASEDIR/cuemol2/bin/cuetty
        env LD_LIBRARY_PATH=$BASEDIR/cuemol2/lib $BASEDIR/cuemol2/bin/cuetty
        
    - name: Download external packages
      if: env.BUILD_MODE == 'full'
      uses: ./build_scripts/download_extpkgs
      with:
        basedir: ${{ github.workspace }}/target

    - name: Build UXP GUI
      if: env.BUILD_MODE == 'full'
      id: build-artifact
      uses: ./build_scripts/build_uxpgui_posix
      with:
        basedir: ${{ github.workspace }}/target

    - name: Upload artifact
      if: env.BUILD_MODE == 'full'
      uses: actions/upload-artifact@v4
      with:
        name: cuemol2_${{ runner.os }}_${{ runner.arch }}
        path: ${{ steps.build-artifact.outputs.artifact-path }}

###############################################

  build_win_x64:
    name: "Windows intel msvc"
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4

    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Setup build envvars
      shell: bash
      run: |
        MSYS_TOP_DIR=$(cygpath -u '${{ github.workspace }}')
        echo "MSYS_TOP_DIR=$MSYS_TOP_DIR" >> $GITHUB_ENV

        MSYS_TOP_DIR2=$(cygpath -m '${{ github.workspace }}')
        echo "MSYS_TOP_DIR2=$MSYS_TOP_DIR2" >> $GITHUB_ENV

        echo NUMBER_OF_PROCESSORS=$NUMBER_OF_PROCESSORS

    - uses: actions/cache@v4
      with:
        path: C:\mozilla-build\
        key: mozbuild-${{ env.mozbuild-cache-version }}
        restore-keys: |
          mozbuild-

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.9

    - name: Enable GitHub Actions Cache backend
      shell: pwsh
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $env:GITHUB_ENV
        echo "SCCACHE_GHA_VERSION=${{ runner.os }}_${{ runner.arch }}" >> $env:GITHUB_ENV

    - name: Find and set sccache path
      shell: cmd
      run: |
        for /f "tokens=*" %%i in ('where sccache') do set SCCACHE_PATH=%%i & goto :done
        :done
        echo SCCACHE_PATH=%SCCACHE_PATH%
        echo SCCACHE_PATH=%SCCACHE_PATH%>> %GITHUB_ENV%

    - name: Download deplibs
      uses: ./build_scripts/download_deplibs
      with:
        basedir: ${{ github.workspace }}/target

    - name: Build libcuemol2
      uses: ./build_scripts/build_libcuemol2_posix
      with:
        basedir: ${{ github.workspace }}\target

    - name: Build and check cuetty
      uses: ./build_scripts/build_cuetty_posix
      with:
        basedir: ${{ github.workspace }}\target

    - name: Make mozconfig
      if: env.BUILD_MODE == 'full'
      shell: bash
      run: bash ${MSYS_TOP_DIR}/build_scripts/build_uxpgui_win/make_mozconfig.sh

    - name: Download external packages
      if: env.BUILD_MODE == 'full'
      uses: ./build_scripts/download_extpkgs
      with:
        basedir: ${{ github.workspace }}/target

    - name: Run mozilla build and build UXP
      if: env.BUILD_MODE == 'full'
      shell: cmd
      run: |
        cmd /c C:\mozilla-build\start-shell.bat %MSYS_TOP_DIR%/build_scripts/build_uxpgui_win/run.sh ${MSYS_TOP_DIR}/target

    - name: Check and copy artifacts
      id: build-artifact
      shell: bash
      env:
        ARTIFACT_NAME: cuemol2_${{ runner.os }}_${{ runner.arch }}.tar.bz2
      run: |
        set -eux
        cd $MSYS_TOP_DIR/uxp_gui
        # obj-x86_64-pc-mingw32/dist/cuemol2-2.3.0.461.win64.installer.exe
        cp obj-x86_64-pc-mingw32/dist/cuemol2-*.installer.exe $MSYS_TOP_DIR/
        cd $MSYS_TOP_DIR
        ls -l cuemol2-*.installer.exe
        tar cjvf $MSYS_TOP_DIR/${ARTIFACT_NAME} cuemol2-*.installer.exe
        echo "artifact-path=${GITHUB_WORKSPACE}/${ARTIFACT_NAME}" >> $GITHUB_OUTPUT

    - name: Upload artifact
      if: env.BUILD_MODE == 'full'
      uses: actions/upload-artifact@v4
      with:
        name: cuemol2_${{ runner.os }}_${{ runner.arch }}
        path: ${{ steps.build-artifact.outputs.artifact-path }}

###############################################

  release_build:
    if: env.BUILD_MODE == 'full'
    needs: [build_posix, build_win_x64]
    runs-on: ubuntu-latest
    steps:
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true
    # - run: |
    #     ls -lR

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: artifacts/*
