name: Build

on:
  pull_request:
    types: [opened, synchronize]
  #    types: [assigned, opened, synchronize, reopened, labeled, unlabeled, edited, closed, ready_for_review, locked, unlocked, review_requested, review_request_removed]

jobs:
  build_win:
    name: "Windows Latest MSVC"
    runs-on: windows-latest
    steps:

    - name: Install prerequisite 1
      run: |
        choco install wget
        choco install winflexbison3

    - uses: actions/checkout@v1

    - name: Install prerequisite 2
      shell: bash
      run: |
        cd ../..
        pwd
        wget https://github.com/CueMol/build_prerequisite/releases/download/v0.0.1/win_build_set.tar.gz -O win_build_set.tar.gz
        tar xzvf win_build_set.tar.gz
        which win_bison.exe
        which win_flex.exe

        # TOPDIR=`pwd`
        # ls -lR $TOPDIR

    - name: Build
      id: build
      shell: cmd
      run: |
        pwd
        mkdir build
        cd build
        cmake .. -G "Visual Studio 16 2019" -A x64 -DCMAKE_PREFIX_PATH=d:\a\win_build -DCGAL_ROOT=d:\a\win_build\CGAL-4.14.3 -DCGAL_DISABLE_GMP=ON -DBUILD_GUI=OFF -DBUILD_PYTHON_BINDINGS=ON
        dir
        cmake --build . -v --config Release
        dir Release

  build_mac:
    name: "MacOS Latest clang"
    runs-on: macos-latest
    steps:

    - name: Install prerequisite 1
      run: |
        brew list
        brew install boost little-cms2 glew
        brew list
        pwd
        
    - uses: actions/checkout@v1

    - name: Install prerequisite 2
      shell: bash
      run: |
        mkdir ${GITHUB_WORKSPACE}/build_prerequisites
        cd ${GITHUB_WORKSPACE}/build_prerequisites
        pwd
        wget https://github.com/CueMol/build_prerequisite/releases/download/v0.0.1/mac_build_set.tar.gz -O mac_build_set.tar.gz
        tar xzf mac_build_set.tar.gz

    - name: Build
      id: build
      run: |
        pwd
        mkdir build
        cd build
        cmake .. -G "Unix Makefiles" -DCGAL_ROOT=${GITHUB_WORKSPACE}/build_prerequisites/GAL-4.14.3 -DCGAL_DISABLE_GMP=ON -DBUILD_GUI=OFF -DBUILD_PYTHON_BINDINGS=ON -DFFTW_ROOT=${GITHUB_WORKSPACE}/build_prerequisites/fftw
        ls -la
        cmake --build . -v --config Release
        ls -la
