name: Build and release

on:
  push:
#    branches-ignore:
#      - '**'

env:
  mozbuild-cache-version: v1
  # uxp-cache-version: v1
  # libcuemol-cache-version: v1

###############################################

jobs:
  build_win_x64:
    name: "Windows intel msvc"
    runs-on: windows-2022
    # runs-on: windows-2019
    steps:
    - uses: actions/checkout@v4

    # - name: Add msbuild to PATH
    #   uses: microsoft/setup-msbuild@v2
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - uses: actions/cache@v4
      with:
        path: C:\mozilla-build\
        key: mozbuild-${{ env.mozbuild-cache-version }}
        restore-keys: |
          mozbuild-

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.9

    - name: Enable GitHub Actions Cache backend
      shell: pwsh
      run: |
        echo "SCCACHE_GHA_ENABLED=true" >> $env:GITHUB_ENV
        echo "SCCACHE_GHA_VERSION=${{ runner.os }}_${{ runner.arch }}" >> $env:GITHUB_ENV
        # echo "SCCACHE_GHA_CACHE_TO=sccache-${{ runner.os }}-${{ github.sha }}" >> $env:GITHUB_ENV
        # echo "SCCACHE_GHA_CACHE_FROM=sccache-${{ runner.os }}-" >> $env:GITHUB_ENV

    - name: Verify sccache config
      run: |
        sccache --version
        sccache --show-stats
        sccache --help

    - name: Install prerequisite
      run: |
        choco install -y -r wget winflexbison3

        $mozilladir = "c:\mozilla-build"
        $src_url = "https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-3.4.exe"
        if((Test-Path $mozilladir) -eq "True"){
          Write-Host "Cache exists"
          dir $mozilladir
        }else{
          Start-BitsTransfer -Source $src_url -Destination ./MozillaBuildSetup.exe
          .\MozillaBuildSetup.exe /S | Out-Null
        }
        dir $mozilladir

    - name: Get repository dirname
      id: get-repos-dir
      shell: bash
      run: |
        set -eux
        sccache -s
        REPOS_DIR=$(echo '${{ github.workspace }}' | sed 's/\\/\//g')
        echo "repos-dir=$REPOS_DIR" >> $GITHUB_OUTPUT
        HOMEPATH_UX=$(echo "$HOMEPATH" | sed 's/\\/\//g')
        echo "home-dir=$HOMEDRIVE$HOMEPATH_UX" >> $GITHUB_OUTPUT

    - name: Download/install deplibs
      shell: bash
      run: |
        set -eux
        TEMP_DIR=$(echo '${{ runner.temp }}' | sed 's/\\/\//g')
        cd $GITHUB_WORKSPACE
        bash build_scripts/download_deplibs/run_windows.sh $TEMP_DIR
        

    - name: Build libcuemol2
      shell: cmd
      run: |
        echo on
        cd %GITHUB_WORKSPACE%
        SET DEPLIBS_DIR=${{ runner.temp }}\proj64_deplibs
        dir %DEPLIBS_DIR%
        cmd /c %GITHUB_WORKSPACE%\build_scripts\build_libcuemol2_win.bat %DEPLIBS_DIR% Release

    - name: Build cuetty
      shell: cmd
      run: |
        echo on
        cd %GITHUB_WORKSPACE%
        set HOME=%HOMEDRIVE%%HOMEPATH%
        cmd /c %GITHUB_WORKSPACE%\build_scripts\build_cuetty_win.bat ${{ runner.temp }}


    - name: Setup build envvars
      shell: bash
      run: |
        BASEDIR=$(echo '${{ runner.temp }}' | sed 's/\\/\//g')
        echo "MSYS_BASEDIR=$BASEDIR" >> $GITHUB_ENV
        DEPLIBS_DIR=$BASEDIR/proj64_deplibs
        echo "MSYS_DEPLIBS_DIR=$DEPLIBS_DIR" >> $GITHUB_ENV
        BUNDLE_DIR=$BASEDIR/cuemol2_bundle
        echo "MSYS_BUNDLE_DIR=$BUNDLE_DIR" >> $GITHUB_ENV

    - name: Edit mozconfig
      shell: bash
      run: |
        set -eux
        cd $GITHUB_WORKSPACE
        # WIN32_REDIST_DIR=$(echo "${VCToolsRedistDir}x64\\Microsoft.VC142.CRT" | sed 's/\\/\//g')
        WIN32_REDIST_DIR=$(echo "${VCToolsRedistDir}x64\\Microsoft.VC143.CRT" | sed 's/\\/\//g')
        echo "$WIN32_REDIST_DIR"
        WIN_UCRT_REDIST_DIR=$(echo "${WindowsSdkDir}Redist\\${WindowsSDKLibVersion}ucrt\\DLLs\\x64" | sed 's/\\/\//g')
        echo "$WIN_UCRT_REDIST_DIR"

        BASEDIR=$MSYS_BASEDIR
        DEPLIBS_DIR=$MSYS_DEPLIBS_DIR
        BUNDLE_DIR=$MSYS_BUNDLE_DIR

        BOOST_DIR=$DEPLIBS_DIR/boost_1_84_0/include/boost-1_84
        LIBDIR=$DEPLIBS_DIR/boost_1_84_0/lib
        CUEMOL_DIR=$DEPLIBS_DIR/cuemol2
        
        cd uxp_gui
        sed "s!@WIN32_REDIST_DIR@!$WIN32_REDIST_DIR!g" $GITHUB_WORKSPACE/build_scripts/mozconfig_Windows \
        | sed "s!@WIN_UCRT_REDIST_DIR@!$WIN_UCRT_REDIST_DIR!g" \
        | sed "s!@CUEMOL_BUNDLE@!$BUNDLE_DIR!g" \
        | sed "s!@CUEMOL_DIR@!$CUEMOL_DIR!g" \
        | sed "s!@BOOST_DIR@!$BOOST_DIR!g" \
        | sed "s!@DEPLIBS_DIR@!$LIBDIR!g" > .mozconfig

        cat .mozconfig

    - name: Run mozilla build and build UXP
      shell: cmd
      run: |
        echo on
        echo ${{ steps.get-repos-dir.outputs.repos-dir }}

        cmd /c C:\mozilla-build\start-shell.bat ${{ steps.get-repos-dir.outputs.repos-dir }}/build_scripts/build_uxpgui_win.sh %MSYS_DEPLIBS_DIR%
